### ISSUE TITLE
The old parser does not parse "$type[] b = new $type[1]" properly?

### ISSUE THREAD

**Issue by danielsun1106** [danielsun1106/groovy-parser#1]
The old parser parses the following statement
```groovy
$type[] b = new $type[1]
```
as
```groovy
$type [[]].call(b = new $type[1])
```
*(src/test/org/codehaus/groovy/classgen/asm/BinaryOperationsTest.groovy)*

I think the statement should be parsed as a declaration statement, which seems advocated by the following original complete script:

```groovy
            $type[] b = new $type[1]
            b[0] = 16
            b[0] |= 2
            assert b[0] == 18:"Failure for type $type"
```

**Comment by danielsun1106** [comment]
@blackdrag
Jochen, could you please confirm it for me? Thanks in advance!

**Comment by blackdrag** [comment]
please not that code of piece is actually in a multi line GString, thus $type is replaced by byte,int,short or long. If you put this code in without being in a multi line string, the it can mean something entirely different. And in that there is the question of if $type is a valid identifier for a class. Your statement suggests it is not, so the next best matching rule will kick in and for that it looks right to me.

**Comment by danielsun1106** [comment]
Jochen, I thought $type was a valid identifier for types(e.g. class, interface, etc.)... As your suggestion, I'll revert the change of identifier recognizing later. Thanks.
