### ISSUE TITLE
Missing 'static' modifiers of inner interface in the interface declaration

### ISSUE THREAD

**Issue by danielsun1106** [danielsun1106/groovy-parser#11]
@blackdrag @paulk-asert

In the interface declaration, the inner interface has different modifiers(no implicit 'static' modifier) with inner class(enum, trait), which will be implicitly added 'static' modifier. Could confirm it for me, bug or feature? Thanks in advance.

``` groovy
interface InvocationSpec {
    interface Builder { // not implicit 'static'
    }
}

interface InvocationSpec {
    class Builder { // implicit 'static'
    }
}

interface InvocationSpec {
    enum Builder { // implicit 'static'
    }
}

interface InvocationSpec {
    trait Builder { // implicit 'static'
    }
}
```

**Comment by blackdrag** [comment]
I don´t see the feature aspect right now, so bug

**Comment by danielsun1106** [comment]
I see :)

**Comment by paulk-asert** [comment]
Where does above come from?

When I run this script:
```
import static java.lang.reflect.Modifier.toString

interface InvocationSpec1 {
    interface Builder1 { // not implicit 'static'
    }
}

interface InvocationSpec2 {
    class Builder2 { // implicit 'static'
    }
}

interface InvocationSpec3 {
    enum Builder3 { // implicit 'static'
        Foo, Bar
    }
}

interface InvocationSpec4 {
    trait Builder4 { // implicit 'static'
    }
}

void pretty(int mod) { println "${mod.toString().padRight(10)}" + toString(mod) }

pretty(InvocationSpec1.Builder1.modifiers)
pretty(InvocationSpec2.Builder2.modifiers)
pretty(InvocationSpec3.Builder3.modifiers)
pretty(InvocationSpec4.Builder4.modifiers)
```
I get this output:
```
1537      public abstract interface
9         public static
16401     public final
1537      public abstract interface
```

**Comment by danielsun1106** [comment]
@paulk-asert 
Paul, I use GroovyConsole's "inspect Ast" to view the dumped AST. I should correct the above test result: the inner enum have no implicit 'static' modifier either. 

| type | has implicit 'static'?|
|------|-----------------|
|inner class| yes| 
|inner trait| yes|
|inner enum| no| 
|inner interface| no| 

```groovy
interface InvocationSpec4 {
    trait Builder4 { // implicit 'static'
    }
}
```
**generates:**
```groovy
@groovy.transform.Trait
public static class InvocationSpec4$Builder4 extends java.lang.Object { 

}
abstract interface public class InvocationSpec4 extends java.lang.Object { 

}
```

**Comment by paulk-asert** [comment]
I don't get static for `InvocationSpec4$Builder4` on master?

**Comment by danielsun1106** [comment]
Paul, groovy-parser is dependent on the groovy-all-2.5.0-SNAPSHOT.jar, which is synched yesterday. I'm not sure groovy-all-2.5.0-SNAPSHOT.jar is build on the newest code of master.

**Comment by danielsun1106** [comment]
I wonder what modifiers should the inner type(in the interface declaration) have? I think the implicit 'static' modifier of interface member seems reasonable. Why do some of inner types have implicit 'static' and others have not?
