### ISSUE TITLE
Provide more friendly error messages

### ISSUE THREAD

**Issue by danielsun1106** [danielsun1106/groovy-parser#12]
We should try to provide more friendly error messages.

@sharwell
Sam, we are using your optimized version of antlr4 to implement a groovy parser, which will be merged into Groovy project.  Could you tell me how to remove the **rule information(e.g. rule parExpression)** of FailedPredicateException?  Thanks in advance!
**PS:** We want to **report the error message and stop parsing right now**.

**current error message:**

```
Script1.groovy: 1: rule parExpression Missing ')' @ line 1, column 7.
   (1 + 2
         ^
```

**expected error message(NO rule information):**

```
Script1.groovy: 1: Missing ')' @ line 1, column 7.
   (1 + 2
         ^
```

**antlr4 code:**

``` antlr
parExpression
    :   LPAREN statementExpression RPAREN

    // !!!Error Alternatives!!!
    |   LPAREN statementExpression               { false }?<fail={ "Missing ')'" }>
    ;
```

_(complete content: https://github.com/danielsun1106/groovy-parser/blob/master/src/main/antlr4/org/apache/groovy/parser/antlr4/GroovyParser.g4)_

**input content:**

``` groovy
(1 + 2
```

**Comment by sharwell** [comment]
Fascinating! I'll take a look.

**Comment by sharwell** [comment]
```antlr
parExpression
    :   LPAREN statementExpression RPAREN

    // !!!Error Alternatives!!!
    |   LPAREN statementExpression               { false }?<fail={ "Missing ')'" }>
    ;

**Comment by sharwell** [comment]
:arrow_right: You need to create an error strategy derived from `DefaultErrorStrategy`, and override [`DefaultErrorStrategy.reportFailedPredicate`](https://github.com/sharwell/antlr4/blob/optimized/runtime/Java/src/org/antlr/v4/runtime/DefaultErrorStrategy.java#L344) to not add the `rule {name}` prefix.

**Comment by danielsun1106** [comment]
As you said, the error alternative impact the parsing performance quite a lot(26min#297 -> 31min#300, https://travis-ci.org/danielsun1106/groovy-parser/builds ).

Thank you, Sam :) I'll give it a try. BTW, your optimized version of antlr4 is quite amazing!

**Comment by sharwell** [comment]
📝 I recently updated my YourKit license and plan to use this test suite for further evaluation of the runtime.

**Comment by danielsun1106** [comment]
In the master branch, groovy-parser contains 10419 test cases, most of which are from famous groovy project, e.g. Grails, Gradle, Spock, Geb and Groovy itself.

The antlr4 branch is using groovy-parser(based on your optimized antlr4) to build and test Groovy programming languange. In addition, the new parser will be used in the Groovy 3. Thanks to your great work achieving the optimized antlr4.
http://ci.groovy-lang.org/viewType.html?buildTypeId=Groovy_Antlr4grammar&guest=1

BTW, after modifying the rule parExpression as the following:
```antlr
parExpression
    :   LPAREN statementExpression
        (   RPAREN
        |   // !!!Error Alternatives!!!
            { false }?<fail={ "Missing ')'" }>
        )
    ;
```
**The error message changed, it seems that the sematic predicate switches on/off some other alternative?**
```
Script1.groovy: 1: no viable alternative at input '<EOF>' @ line 1, column 7.
   (1 + 2
         ^
```
**Before modified:**
```
Script1.groovy: 1: rule parExpression Missing ')' @ line 1, column 7.
   (1 + 2
         ^
```

**Comment by danielsun1106** [comment]
@sharwell
Sam, I use `assert` to interrupt the parsing when occurred in the lexer. Is there any other elegant way to throw an exception to complete the same thing? Thanks in advance!

*current code:*
```java
assert null != paren: "Too many '" + text + "' " + genPositionInfo();
assert text.equals(PAREN_MAP.get(paren)): "'" + text + "' can not match '" + paren + "' " + genPositionInfo();
```

*experimental code(fails to stop parsing when lexer error occurred):*
```java
        if (null == paren) {
            throw new RuntimeException("Too many '" + text + "' " + genPositionInfo());
        }
        if (!text.equals(PAREN_MAP.get(paren))) {
            throw new RuntimeException("'" + text + "' can not match '" + paren + "' " + genPositionInfo());
        }
```

**Comment by sharwell** [comment]
@danielsun1106 The file [PostgreSqlLexer.g4](https://github.com/tunnelvisionlabs/antlr4-grammar-postgresql/blob/master/src/com/tunnelvisionlabs/postgresql/PostgreSqlLexer.g4) contains what I believe is the strongest example to date of a robust lexer. The comments describe the mechanisms used to handle a variety of input errors.

**Comment by danielsun1106** [comment]
Thanks a lot, Sam. I'll try later :)

**Comment by danielsun1106** [comment]
@sharwell 
Sam, I tried to check the missing RPAREN. The original way is inefficient but genenates better error messages, and the efficient way you provided has better performance but generates confused error messages. Could you tell me how to improve the error message of the efficient way? Thanks in advance!

**input text:**
```
 (1 + 2
```

**efficient way:**
```antlr
parExpression
    :   LPAREN statementExpression
        (   RPAREN
        |   // !!!Error Alternatives!!!
            { false }?<fail={ "Missing ')'" }>
        )
    ;
```
**error message of efficient way:**
```
Script1.groovy: 1: no viable alternative at input '<EOF>' @ line 1, column 7.
   (1 + 2
         ^
```

**Comment by sharwell** [comment]
Error handling in ANTLR 4 is very interesting. There are two goals we're trying to achieve: good error reporting, and good error recovery. It turns out that ANTLR is quite good at both reporting and recovery for errors that occur where decisions are LL(1). For other cases, the current implementation appears to favor recovery over reporting (not necessarily the intent, but this is my observation).

Back when I was working on GoWorks, I decided to experiment with an alternate error handling strategy. To me, it seemed strange that `adaptivePredict` would look ahead several symbols, and then fail to return any decision at all if it encountered an error later in the input. In my experiment, I modified `adaptivePredict` so that a syntax error occurring at LL(k>1) would cause `adaptivePredict` return the "best known answer so far", which really meant returning the minimum alternative number which successfully matched input leading to the error. The result was fascinating - the strategy had near perfect localization and reporting for the first syntax error in a file, but the recovery was just a disaster (numerous errors were reported through the remainder of the file, suggesting that the parser had no idea what to do after the first error).

The answer to this probably lies in a hybrid approach. Consider the following:

1. Parse the file using an error handler with good recovery characteristics, but don't report syntax errors.
2. For each node in the parse tree which contains a sequence of tokens skipped by the error recovery, attempt to re-parse that node using a recovery strategy with good localization. Stop after reporting the first error since we're not relying on this step for recovery.

I haven't implemented anything like this yet, but I imagine it would do quite well with grammars, especially if/where semantic predicates can be avoided.

**Comment by danielsun1106** [comment]
Hi Sam,

      Thanks for your explaining the internals to me in detail ;)
      As to the 2 approaches, we can not choose the first one because Groovy should help developers locate syntax errors instead of fixing them automatically. The second approach seems better to apply, could you provide some examples or some reference documentations?

Thanks,
Daniel.Sun

在 2016年11月29日 上午2:09，Sam Harwell <notifications@github.com>写道：

Error handling in ANTLR 4 is very interesting. There are two goals we're trying to achieve: good error reporting, and good error recovery. It turns out that ANTLR is quite good at both reporting and recovery for errors that occur where decisions are LL(1). For other cases, the current implementation appears to favor recovery over reporting (not necessarily the intent, but this is my observation).

Back when I was working on GoWorks, I decided to experiment with an alternate error handling strategy. To me, it seemed strange that adaptivePredict would look ahead several symbols, and then fail to return any decision at all if it encountered an error later in the input. In my experiment, I modified adaptivePredict so that a syntax error occurring at LL(k>1) would cause adaptivePredict return the "best known answer so far", which really meant returning the minimum alternative number which successfully matched input leading to the error. The result was fascinating - the strategy had near perfect localization and reporting for the first syntax error in a file, but the recovery was just a disaster (numerous errors were reported through the remainder of the file, suggesting that the parser had no idea what to do after the first error).

The answer to this probably lies in a hybrid approach. Consider the following:

  1.  Parse the file using an error handler with good recovery characteristics, but don't report syntax errors.
  2.  For each node in the parse tree which contains a sequence of tokens skipped by the error recovery, attempt to re-parse that node using a recovery strategy with good localization. Stop after reporting the first error since we're not relying on this step for recovery.

I haven't implemented anything like this yet, but I imagine it would do quite well with grammars, especially if/where semantic predicates can be avoided.

**Comment by danielsun1106** [comment]
@sharwell 

I'm trying to throw GroovySyntaxError and find that the approach works fine. Now I'm looking for the general way to get line and column of the position where throwing error.
```antlr
parExpression
    :   LPAREN (statementExpression | standardLambda)
        (   RPAREN
        |   { if (true) throw new GroovySyntaxError("Missing ')'"); }
        )
```

**Comment by danielsun1106** [comment]
@sharwell
I find throw GroovySyntaxError works fine in lexer(https://github.com/danielsun1106/groovy-parser/commit/54889f5dc4ff1b7d2346c6c62a92695b14db5694), 
but the approach does not fit parser... because some test cases fails. I guess antlr4 will trigger the throwing GroovySyntaxError action when choosing alternatives. `LPAREN` and `RPAREN` are not used in  rule `parExpression` only, rule `formalParameters` uses `LPAREN` and `RPAREN` as well, so when antlr4 try to match rule `parExpression`  and failed, it triggers the throwing GroovySyntaxError action of rule `parExpression` . Could you confirm it for me? Thanks in advance!

**Comment by danielsun1106** [comment]
@sharwell 
I address the issue that some test cases fail when adding throw error action.
It's because I use the two stage parsing strategy and the SLL mode triggers the action :)
