### ISSUE TITLE
org.codehaus.groovy.runtime.typehandling.GroovyCastException in Groovy ".with { ... }" - Block

### ISSUE THREAD

**Issue by OldSparkyMI** [danielsun1106/groovy-parser#18]
I already opened a JIRA: https://issues.apache.org/jira/browse/GROOVY-7701
Bug still occurs with the current version of your parser.

**Comment by danielsun1106** [comment]
@OldSparkyMI the issue is not related to parser, so reporting it in the Groovy JIRA is a better choice :)
