### ISSUE TITLE
Question about the form of `sep`

### ISSUE THREAD

**Issue by sharwell** [danielsun1106/groovy-parser#27]
Can you explain why `sep` is not written like this? I'm specifically interested in understanding if the behavior is a language limitation or just a grammar oversight. Note that the form I used in the following example is meant as an example; I intended to optimize for clarity here, not performance.

```antlr
sep : NL* (SEMI NL*)+ ;
```

**Comment by danielsun1106** [comment]
SEMI is optional in Groovy.

**Comment by sharwell** [comment]
@danielsun1106 Yes, but notice the difference between what I wrote above and what appears in the grammar:

https://github.com/danielsun1106/groovy-parser/blob/7dc164578113352fa76426d8a78bf1008b6ecefc/src/main/antlr/GroovyParser.g4#L1213-L1215

The number of semicolons allowed as a separator depends on whether the first separator is placed on the same line or after one or more newlines.

**Comment by sharwell** [comment]
Oh I see, the intent is to allow at least one newline or semicolon, but more are allowed. So we want this:

```
sep
  : (NL | SEMI)+
  ;
```

**Comment by danielsun1106** [comment]
I've refined the `sep` rule according to your suggestion, thanks :-)
https://github.com/danielsun1106/groovy-parser/commit/bbd2c87c071d07683f8a4ca35a206f2d8032b9ac
