### ISSUE TITLE
The old parser parse 'if statement' as an unexpected AST

### ISSUE THREAD

**Issue by danielsun1106** [danielsun1106/groovy-parser#4]
@blackdrag  @paulk-asert
Hi Jochen, Paul
     I find the old parser parse 'if statement' as an unexpected AST, which I think is not correct. Could you confirm it for me? Thanks in advance.

```groovy
if (false)
    int x = 2, y = 1
```
will be parsed as
**ACTUAL**
```groovy
if (false) {
    java.lang.Integer x = 2
} else {
    java.lang.Integer y = 1
}
```
**EXPECTED**
```groovy
if (false) {
    java.lang.Integer x = 2
    java.lang.Integer y = 1
} 
```

Cheers,
Daniel.Sun

**Comment by paulk-asert** [comment]
At first glance, looks like a bug to me.

**Comment by danielsun1106** [comment]
@paulk-asert
Paul, any plan to fix the bug in the old parser? or leave it to the new parser?

**Comment by paulk-asert** [comment]
I think we should fix that if it isn't too hard. Worth an issue I think -
which we can always close later.

**Comment by paulk-asert** [comment]
I think we should fix that if it isn't too hard. Worth an issue I think -
which we can always close later. We'd need to replace
`int x = 2, y = 1`
on the fly with either one of these I think:
`{ int x = 2; int y = 1 }`
`def (int x, int y) = [2, 1]`

**Comment by danielsun1106** [comment]
OK, I'll follow your steps :)

**Comment by paulk-asert** [comment]
Looks like this is wrong too:
`while (false) int x = 2, y = 1`

**Comment by danielsun1106** [comment]
Yeah, the following code is also wrong:

```
for(;;) int x = 2, y = 1
```
is parsed as
```
for (;;) {
    java.lang.Integer x = 2}
```

**Comment by paulk-asert** [comment]
I created this issue to track fixing this for the old parser:
https://issues.apache.org/jira/browse/GROOVY-7958

**Comment by danielsun1106** [comment]
OK, I'll fix it in the new parser and test when the issue is closed.

**Comment by paulk-asert** [comment]
Fix commited on the apache/groovyt repo.

**Comment by danielsun1106** [comment]
OK, I'll fix it in the new parser too later.
